server:
  port: 8082

spring:
  application:
    name: springclood-demo2

#中间件注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5   #心跳间隔设置  5秒
    lease-expiration-duration-in-seconds: 10  #没有心跳的淘汰时间设计 10秒
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/  #中间件注册中心配置，默认使用用户密码登录
    registry-fetch-interval-seconds: 5  #定时刷新本地环境时间设置
