server:
  port: 8080

#中间件注册中心用户配置
spring:
  security:
    user:
      name: wsb
      password: wsb
  application:
    name: arrail-eureka-business-server

#中间件注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5  # 客户端从Eureka Server集群里更新Eureka Server信息的频率
    lease-expiration-duration-in-seconds: 10 # 没有心跳的淘汰时间
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.name}@${eureka.instance.hostname}:8080/eureka/  #中间件注册中地址，默认使用用户名yw，密码yw进入
    register-with-eureka: false
    fetch-registry: false
    eureka-service-url-poll-interval-seconds: 60 # 客户端从Eureka Server集群里更新Eureka Server信息的频率
  server:
    enable-self-preservation: false  # 关闭自我保护
    eviction-interval-timer-in-ms: 5000   # 主动失效检测间隔,配置成5秒
    use-read-only-response-cache: false # 禁用readOnlyCacheMap
